# Makefile, autogenerated by mfjen
# Edit at will, regenerating obliterates changes, fair warning

COMPILER=gcc

FLAGS:=-lpng

COMPILEFLAGS=$(FLAGS) -Isrc -lGL -lGLU -lglut -ggdb -std=c11 
LINKFLAGS=$(FLAGS) -Isrc -lGL -lGLU -lglut -ggdb -std=c11 

HEADERS=$(wildcard src/*.h) $(wildcard src/*/*.h)
PROGRAMOBJECTS=$(patsubst src/%.c,obj/%.o,$(wildcard src/*.c)) $(patsubst src/%.c,obj/%.o,$(wildcard src/*/*.c))

# Just change value of PROGRAMNAME when good name is found
PROGRAMNAME=game
PROGRAMFILE=$(if $(PROGRAMNAME),bin/$(PROGRAMNAME).$(shell arch),bin/$(notdir $(shell pwd)).$(shell arch))

all: $(PROGRAMFILE)

obj/%.o: src/%.c $(HEADERS)
	$(COMPILER) -c -o $@ $< $(COMPILEFLAGS) -fPIC

$(PROGRAMFILE): $(PROGRAMOBJECTS)
	$(COMPILER) -o $(PROGRAMFILE) $(PROGRAMOBJECTS) $(LINKFLAGS)

