# Makefile, autogenerated by mfjen
# Edit at will, regenerating obliterates changes, fair warning

# Change when a good name is found
GAME_NAME=$(shell basename $(shell pwd))

COMPILER=gcc

FLAGS:=-lpng

COMPILEFLAGS=$(FLAGS) -Isrc -lGL -lGLU -lglut -ggdb -std=c11 
LINKFLAGS=$(FLAGS) -Isrc -lGL -lGLU -lglut -ggdb -std=c11 

HEADERS=$(wildcard src/*.h) $(wildcard src/*/*.h)
PROGRAMOBJECTS=$(patsubst src/%.c,obj/%.o,$(wildcard src/*.c)) $(patsubst src/%.c,obj/%.o,$(wildcard src/*/*.c))

PROGRAM=bin/$(GAME_NAME).$(shell arch)

all: $(PROGRAM)

obj/%.o: src/%.c $(HEADERS)
	$(COMPILER) -c -o $@ $< $(COMPILEFLAGS) -fPIC

$(PROGRAM): $(PROGRAMOBJECTS)
	$(COMPILER) -o $(PROGRAM) $(PROGRAMOBJECTS) $(LINKFLAGS)

